//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineOrdersManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal Sum { get; set; }
        public int ClientID { get; set; }
        public int StatusID { get; set; }
        public string ProductsItems { get; set; }
        public string ClientComment { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
